[package]
name = "Eiffel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.9.2"
bson = "2.5.0"
parking_lot = "0.12.1"
tokio = {version = "1.25.0", features = ["full"]}